name: Build nutritrack-apis-get-product-by-id-docker-file-and-push-to-ECR

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:      
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        cd nutritrack-apis/get-product-by-id
        docker build . --tag nutritrack-api/get-product-by-id:latest
        docker tag nutritrack-api/get-product-by-id:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nutritrack-api/get-product-by-id:latest
  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
    
    - name: login to amazon ecr
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Push to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nutritrack-api/get-product-by-id:latest
