# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: nutritrack-apis-get-product-by-id-build

on:
  push:
    paths:
      - 'nutritrack-apis/get-product-by-id/*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd nutritrack-apis/get-product-by-id
        python -m pip install --upgrade pip
        pip install flake8 pytest responses
        if [ -f nutritrack-apis/get-product-by-id/requirements.txt ]; then pip install -r nutritrack-apis/get-product-by-id/requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd nutritrack-apis/get-product-by-id
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest nutritrack-apis/get-product-by-id/tests/
