name: build get-products-api application

on:
  push:
    paths:
      - 'nutritrack-apis/get-products/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd nutritrack-apis/get-products/
        npm install
        tsc
        
